const fs = require('fs');
let code = fs.readFileSync('c:/Users/isaac/taskflow/taskflow/src/utils/constants.js', 'utf8');

const newLangs = `export const LANGS = {
  en: {
    name: "English", flag: "🇬🇧", t: {
      appName: "StarredList", tasks: "Tasks", add: "Add Task", done: "Done", active: "Active",
      overdue: "Overdue", total: "Total", today: "Today", starred: "Starred", assistant: "Assistant",
      stats: "Statistics", calendar: "Calendar", settings: "Settings", profiles: "Profiles",
      newTask: "New Task", editTask: "Edit Task", save: "Save", cancel: "Cancel",
      title: "Title", notes: "Notes", priority: "Priority", category: "Category", dueDate: "Due Date",
      tags: "Tags", subtasks: "Subtasks", photo: "Photo", recurring: "Recurring", reminder: "Reminder",
      high: "High", medium: "Medium", low: "Low", noTasks: "No tasks here!", addFirst: "Tap + to add your first task",
      completionRate: "Completion Rate", thisWeek: "This Week", byCategory: "By Category", byPriority: "By Priority",
      export: "Export", share: "Share", lock: "App Lock", theme: "Theme", language: "Language", sound: "Sound",
      notifications: "Notifications", profile: "Profile", switchProfile: "Switch Profile", newProfile: "New Profile",
      pinLock: "PIN Lock", enterPin: "Enter PIN", setPin: "Set PIN", wrongPin: "Wrong PIN, try again",
      unlock: "Unlock", confirmPin: "Confirm PIN", pinsNoMatch: "PINs don't match",
      daily: "Daily", weekly: "Weekly", monthly: "Monthly", never: "Never",
      accentColor: "Accent Color", darkMode: "Dark Mode", completed: "Completed",
      // New additions:
      goals: "Goals", habits: "Habits", planner: "Daily Planner", collab: "Collaborate", board: "Board", bot: "LIBI AI",
      appearanceHelp: "Appearance, account & preferences", account: "Account",
      signedInWith: "Signed in with Google", signInWith: "Sign in with Google", syncTasks: "Sync tasks across devices",
      signOut: "Sign out", lightMode: "Light Mode", tapSwitchTheme: "Tap to switch theme",
      notifSound: "Notifications & Sound", getReminded: "Get reminded about due tasks",
      soundEffects: "Sound effects on actions", integrations: "Integrations", exportPdf: "Export to PDF",
      weeklyReport: "Weekly report of tasks & progress", installApp: "Install App",
      addAppHome: "Add StaredList to your home screen", security: "Security",
      setPinLock: "Set PIN Lock", changePin: "Change PIN", protectApp: "Protect your app with a 4-digit PIN",
      pinActive: "App is PIN protected 🔒", activeStatus: "Active", privacyPolicy: "Privacy Policy", termsOfService: "Terms of Service"
    }
  },
  ar: {
    name: "العربية", flag: "🇸🇦", t: {
      appName: "تاسك فلو", tasks: "المهام", add: "إضافة مهمة", done: "منجز", active: "نشط",
      overdue: "متأخر", total: "المجموع", today: "اليوم", starred: "المميزة", assistant: "المساعد",
      stats: "الإحصائيات", calendar: "التقويم", settings: "الإعدادات", profiles: "الملفات",
      newTask: "مهمة جديدة", editTask: "تعديل المهمة", save: "حفظ", cancel: "إلغاء",
      title: "العنوان", notes: "ملاحظات", priority: "الأولوية", category: "الفئة", dueDate: "تاريخ الاستحقاق",
      tags: "الوسوم", subtasks: "المهام الفرعية", photo: "صورة", recurring: "متكرر", reminder: "تذكير",
      high: "عالي", medium: "متوسط", low: "منخفض", noTasks: "لا توجد مهام!", addFirst: "اضغط + لإضافة مهمة",
      completionRate: "معدل الإنجاز", thisWeek: "هذا الأسبوع", byCategory: "حسب الفئة", byPriority: "حسب الأولوية",
      export: "تصدير", share: "مشاركة", lock: "قفل التطبيق", theme: "المظهر", language: "اللغة", sound: "الصوت",
      notifications: "الإشعارات", profile: "الملف", switchProfile: "تبديل الملف", newProfile: "ملف جديد",
      pinLock: "قفل PIN", enterPin: "أدخل PIN", setPin: "تعيين PIN", wrongPin: "PIN خاطئ",
      unlock: "فتح", confirmPin: "تأكيد PIN", pinsNoMatch: "PINs لا تتطابق",
      daily: "يومي", weekly: "أسبوعي", monthly: "شهري", never: "أبداً",
      accentColor: "لون التمييز", darkMode: "الوضع الداكن", completed: "مكتمل",
      goals: "الأهداف", habits: "العادات", planner: "المخطط اليومي", collab: "التعاون", board: "لوحة", bot: "الذكاء LIBI",
      appearanceHelp: "المظهر، الحساب والتفضيلات", account: "الحساب",
      signedInWith: "مسجل الدخول بجوجل", signInWith: "تسجيل الدخول بجوجل", syncTasks: "مزامنة المهام",
      signOut: "تسجيل الخروج", lightMode: "الوضع الفاتح", tapSwitchTheme: "انقر لتبديل المظهر",
      notifSound: "الإشعارات والصوت", getReminded: "تذكير بالمهام المستحقة",
      soundEffects: "مؤثرات صوتية للإجراءات", integrations: "التكاملات", exportPdf: "تصدير إلى PDF",
      weeklyReport: "تقرير أسبوعي للمهام والتقدم", installApp: "تثبيت التطبيق",
      addAppHome: "أضف StaredList لشاشتك الرئيسية", security: "الأمان",
      setPinLock: "تعيين قفل PIN", changePin: "تغيير PIN", protectApp: "قم بحماية تطبيقك برمز PIN من 4 أرقام",
      pinActive: "التطبيق محمي بـ PIN 🔒", activeStatus: "نشط", privacyPolicy: "سياسة الخصوصية", termsOfService: "شروط الخدمة"
    }
  },
  hi: {
    name: "हिन्दी", flag: "🇮🇳", t: {
      appName: "टास्कफ्लो", tasks: "कार्य", add: "कार्य जोड़ें", done: "पूर्ण", active: "सक्रिय",
      overdue: "विलंबित", total: "कुल", today: "आज", starred: "तारांकित", assistant: "सहायक",
      stats: "आँकड़े", calendar: "कैलेंडर", settings: "सेटिंग", profiles: "प्रोफाइल",
      newTask: "नया कार्य", editTask: "कार्य संपादित करें", save: "सहेजें", cancel: "रद्द करें",
      title: "शीर्षक", notes: "नोट्स", priority: "प्राथमिकता", category: "श्रेणी", dueDate: "नियत तिथि",
      tags: "टैग", subtasks: "उप-कार्य", photo: "फ़ोटो", recurring: "आवर्ती", reminder: "अनुस्मारक",
      high: "उच्च", medium: "मध्यम", low: "निम्न", noTasks: "यहाँ कोई कार्य नहीं!", addFirst: "+ दबाएं",
      completionRate: "पूर्णता दर", thisWeek: "इस सप्ताह", byCategory: "श्रेणी अनुसार", byPriority: "प्राथमिकता अनुसार",
      export: "निर्यात", share: "साझा करें", lock: "ऐप लॉक", theme: "थीम", language: "भाषा", sound: "ध्वनि",
      notifications: "सूचनाएं", profile: "प्रोफ़ाइल", switchProfile: "प्रोफ़ाइल बदलें", newProfile: "नया प्रोफ़ाइल",
      pinLock: "PIN लॉक", enterPin: "PIN दर्ज करें", setPin: "PIN सेट करें", wrongPin: "गलत PIN",
      unlock: "अनलॉक", confirmPin: "PIN पुष्टि करें", pinsNoMatch: "PIN मेल नहीं खाते",
      daily: "दैनिक", weekly: "साप्ताहिक", monthly: "मासिक", never: "कभी नहीं",
      accentColor: "एक्सेंट रंग", darkMode: "डार्क मोड", completed: "पूर्ण",
      goals: "लक्ष्य", habits: "आदतें", planner: "दैनिक योजनाकार", collab: "सहयोग", board: "बोर्ड", bot: "LIBI AI",
      appearanceHelp: "दिखावट, खाता और प्राथमिकताएं", account: "खाता",
      signedInWith: "Google से साइन इन", signInWith: "Google के साथ साइन इन करें", syncTasks: "कार्यों को सिंक करें",
      signOut: "साइन आउट", lightMode: "लाइट मोड", tapSwitchTheme: "थीम बदलने के लिए टैप करें",
      notifSound: "सूचनाएं और ध्वनि", getReminded: "नियत कार्यों के बारे में याद दिलाएं",
      soundEffects: "कार्यों पर ध्वनि प्रभाव", integrations: "एकहीकरण", exportPdf: "PDF में निर्यात करें",
      weeklyReport: "कार्यों और प्रगति की साप्ताहिक रिपोर्ट", installApp: "ऐप इंस्टॉल करें",
      addAppHome: "StaredList को होम स्क्रीन में जोड़ें", security: "सुरक्षा",
      setPinLock: "PIN लॉक सेट करें", changePin: "PIN बदलें", protectApp: "4-अंकीय PIN से ऐप सुरक्षित करें",
      pinActive: "ऐप PIN संरक्षित है 🔒", activeStatus: "सक्रिय", privacyPolicy: "गोपनीयता नीति", termsOfService: "सेवा की शर्तें"
    }
  },
  fr: {
    name: "Français", flag: "🇫🇷", t: {
      appName: "StarredList", tasks: "Tâches", add: "Ajouter", done: "Terminé", active: "Actif",
      overdue: "En retard", total: "Total", today: "Aujourd'hui", starred: "Favoris", assistant: "Assistant",
      stats: "Statistiques", calendar: "Calendrier", settings: "Paramètres", profiles: "Profils",
      newTask: "Nouvelle", editTask: "Modifier", save: "Sauvegarder", cancel: "Annuler",
      title: "Titre", notes: "Notes", priority: "Priorité", category: "Catégorie", dueDate: "Échéance",
      tags: "Tags", subtasks: "Sous-tâches", photo: "Photo", recurring: "Récurrent", reminder: "Rappel",
      high: "Haute", medium: "Moyenne", low: "Basse", noTasks: "Aucune tâche!", addFirst: "Appuyez sur +",
      completionRate: "Taux de complétion", thisWeek: "Cette semaine", byCategory: "Par catégorie", byPriority: "Par priorité",
      export: "Exporter", share: "Partager", lock: "Verrou", theme: "Thème", language: "Langue", sound: "Son",
      notifications: "Notifications", profile: "Profil", switchProfile: "Changer profil", newProfile: "Nouveau",
      pinLock: "Verrou PIN", enterPin: "Entrer PIN", setPin: "Définir PIN", wrongPin: "PIN incorrect",
      unlock: "Déverrouiller", confirmPin: "Confirmer PIN", pinsNoMatch: "Différents",
      daily: "Quotidien", weekly: "Hebdo", monthly: "Mensuel", never: "Jamais",
      accentColor: "Couleur", darkMode: "Mode sombre", completed: "Complété",
      goals: "Objectifs", habits: "Habitudes", planner: "Agenda", collab: "Collaborer", board: "Tableau", bot: "LIBI AI",
      appearanceHelp: "Apparence, compte et préférences", account: "Compte",
      signedInWith: "Connecté avec Google", signInWith: "Se connecter avec Google", syncTasks: "Synchroniser les tâches",
      signOut: "Se déconnecter", lightMode: "Mode clair", tapSwitchTheme: "Appuyez pour changer le thème",
      notifSound: "Notifications & Son", getReminded: "Soyez rappelé des tâches",
      soundEffects: "Effets sonores", integrations: "Intégrations", exportPdf: "Exporter en PDF",
      weeklyReport: "Rapport hebdomadaire", installApp: "Installer l'App",
      addAppHome: "Ajouter à l'écran d'accueil", security: "Sécurité",
      setPinLock: "Définir verrou PIN", changePin: "Changer le PIN", protectApp: "Protéger avec un code à 4 chiffres",
      pinActive: "App protégée par PIN 🔒", activeStatus: "Actif", privacyPolicy: "Confidentialité", termsOfService: "Conditions"
    }
  },
  es: {
    name: "Español", flag: "🇪🇸", t: {
      appName: "StarredList", tasks: "Tareas", add: "Agregar", done: "Hecho", active: "Activo",
      overdue: "Atrasado", total: "Total", today: "Hoy", starred: "Favoritos", assistant: "Asistente",
      stats: "Estadísticas", calendar: "Calendario", settings: "Ajustes", profiles: "Perfiles",
      newTask: "Nueva", editTask: "Editar", save: "Guardar", cancel: "Cancelar",
      title: "Título", notes: "Notas", priority: "Prioridad", category: "Categoría", dueDate: "Fecha límite",
      tags: "Etiquetas", subtasks: "Subtareas", photo: "Foto", recurring: "Recurrente", reminder: "Recordatorio",
      high: "Alta", medium: "Media", low: "Baja", noTasks: "¡Sin tareas!", addFirst: "Toca + para agregar",
      completionRate: "Tasa completado", thisWeek: "Esta semana", byCategory: "Por categoría", byPriority: "Por prioridad",
      export: "Exportar", share: "Compartir", lock: "Bloqueo", theme: "Tema", language: "Idioma", sound: "Sonido",
      notifications: "Notificaciones", profile: "Perfil", switchProfile: "Cambiar perfil", newProfile: "Nuevo",
      pinLock: "Bloqueo PIN", enterPin: "Ingresar PIN", setPin: "Establecer PIN", wrongPin: "PIN malo",
      unlock: "Desbloquear", confirmPin: "Confirmar PIN", pinsNoMatch: "PINs no coinciden",
      daily: "Diario", weekly: "Semanal", monthly: "Mensual", never: "Nunca",
      accentColor: "Color de acento", darkMode: "Modo oscuro", completed: "Completado",
      goals: "Metas", habits: "Hábitos", planner: "Agenda diaria", collab: "Colaborar", board: "Tablero", bot: "LIBI AI",
      appearanceHelp: "Apariencia, cuenta y preferencias", account: "Cuenta",
      signedInWith: "Ingresó con Google", signInWith: "Ingresar con Google", syncTasks: "Sincronizar tareas",
      signOut: "Cerrar sesión", lightMode: "Modo claro", tapSwitchTheme: "Toca para cambiar de tema",
      notifSound: "Notificaciones y Sonido", getReminded: "Recibe recordatorios de tareas",
      soundEffects: "Efectos de sonido", integrations: "Integraciones", exportPdf: "Exportar a PDF",
      weeklyReport: "Informe semanal y progreso", installApp: "Instalar App",
      addAppHome: "Añadir a la pantalla de inicio", security: "Seguridad",
      setPinLock: "Establecer Bloqueo", changePin: "Cambiar PIN", protectApp: "Protege con un PIN de 4 dígitos",
      pinActive: "App protegida por PIN 🔒", activeStatus: "Activo", privacyPolicy: "Privacidad", termsOfService: "Términos"
    }
  },
  de: {
    name: "Deutsch", flag: "🇩🇪", t: {
      appName: "StarredList", tasks: "Aufgaben", add: "Hinzufügen", done: "Erledigt", active: "Aktiv",
      overdue: "Überfällig", total: "Gesamt", today: "Heute", starred: "Favoriten", assistant: "Assistent",
      stats: "Statistiken", calendar: "Kalender", settings: "Einstellungen", profiles: "Profile",
      newTask: "Neue", editTask: "Bearbeiten", save: "Speichern", cancel: "Abbrechen",
      title: "Titel", notes: "Notizen", priority: "Priorität", category: "Kategorie", dueDate: "Fälligkeit",
      tags: "Tags", subtasks: "Teilaufgaben", photo: "Foto", recurring: "Wiederkehrend", reminder: "Erinnerung",
      high: "Hoch", medium: "Mittel", low: "Niedrig", noTasks: "Keine Aufgaben!", addFirst: "Tippe auf +",
      completionRate: "Abschlussquote", thisWeek: "Diese Woche", byCategory: "Nach Kategorie", byPriority: "Nach Priorität",
      export: "Exportieren", share: "Teilen", lock: "Sperre", theme: "Thema", language: "Sprache", sound: "Ton",
      notifications: "Benachrichtigungen", profile: "Profil", switchProfile: "Profil wechseln", newProfile: "Neues",
      pinLock: "PIN-Sperre", enterPin: "PIN eingeben", setPin: "PIN festlegen", wrongPin: "Falsche PIN",
      unlock: "Entsperren", confirmPin: "PIN bestätigen", pinsNoMatch: "Stimmt nicht überein",
      daily: "Täglich", weekly: "Wöchentlich", monthly: "Monatlich", never: "Nie",
      accentColor: "Akzentfarbe", darkMode: "Dunkel", completed: "Erledigt",
      goals: "Ziele", habits: "Gewohnheiten", planner: "Tagesplaner", collab: "Mitwirken", board: "Tafel", bot: "LIBI AI",
      appearanceHelp: "Erscheinungsbild, Konto & Präferenzen", account: "Konto",
      signedInWith: "Angemeldet mit Google", signInWith: "Mit Google anmelden", syncTasks: "Aufgaben synchronisieren",
      signOut: "Abmelden", lightMode: "Hell", tapSwitchTheme: "Tippen fürs Thema",
      notifSound: "Benachrichtigungen & Ton", getReminded: "Werde an Aufgaben erinnert",
      soundEffects: "Soundeffekte", integrations: "Integrationen", exportPdf: "Als PDF exportieren",
      weeklyReport: "Wöchentlicher Fortschrittsbericht", installApp: "App installieren",
      addAppHome: "Zum Startbildschirm hinzufügen", security: "Sicherheit",
      setPinLock: "PIN-Sperre einrichten", changePin: "PIN ändern", protectApp: "Schütze mit 4-stelliger PIN",
      pinActive: "App ist durch PIN geschützt 🔒", activeStatus: "Aktiv", privacyPolicy: "Datenschutz", termsOfService: "Bedingungen"
    }
  },
  pt: {
    name: "Português", flag: "🇵🇹", t: {
      appName: "StarredList", tasks: "Tarefas", add: "Adicionar", done: "Feito", active: "Ativo",
      overdue: "Atrasado", total: "Total", today: "Hoje", starred: "Favoritos", assistant: "Assistente",
      stats: "Estatísticas", calendar: "Calendário", settings: "Definições", profiles: "Perfis",
      newTask: "Nova", editTask: "Editar", save: "Salvar", cancel: "Cancelar",
      title: "Título", notes: "Notas", priority: "Prioridade", category: "Categoria", dueDate: "Prazo",
      tags: "Tags", subtasks: "Subtarefas", photo: "Foto", recurring: "Recorrente", reminder: "Lembrete",
      high: "Alta", medium: "Média", low: "Baixa", noTasks: "Sem tarefas!", addFirst: "Toque em +",
      completionRate: "Taxa de conclusão", thisWeek: "Esta semana", byCategory: "Por categoria", byPriority: "Por prioridade",
      export: "Exportar", share: "Partilhar", lock: "Bloqueio", theme: "Tema", language: "Idioma", sound: "Som",
      notifications: "Notificações", profile: "Perfil", switchProfile: "Trocar perfil", newProfile: "Novo",
      pinLock: "Bloqueio PIN", enterPin: "Inserir PIN", setPin: "Definir PIN", wrongPin: "PIN errado",
      unlock: "Desbloquear", confirmPin: "Confirmar PIN", pinsNoMatch: "Diferentes",
      daily: "Diário", weekly: "Semanal", monthly: "Mensal", never: "Nunca",
      accentColor: "Cor de Destaque", darkMode: "Modo escuro", completed: "Completo",
      goals: "Metas", habits: "Hábitos", planner: "Agenda", collab: "Colaborar", board: "Quadro", bot: "LIBI AI",
      appearanceHelp: "Aparência, conta e preferências", account: "Conta",
      signedInWith: "Conectado com Google", signInWith: "Entrar com Google", syncTasks: "Sincronizar tarefas",
      signOut: "Sair", lightMode: "Modo Claro", tapSwitchTheme: "Toque para mudar assunto",
      notifSound: "Notificações e Som", getReminded: "Lembretes de tarefas",
      soundEffects: "Efeitos sonoros", integrations: "Integrações", exportPdf: "Exportar para PDF",
      weeklyReport: "Relatório semanal de progresso", installApp: "Instalar App",
      addAppHome: "Adicionar ao Ecrã Principal", security: "Segurança",
      setPinLock: "Definir Bloqueio PIN", changePin: "Mudar PIN", protectApp: "Proteja o app com um PIN de 4 dígitos",
      pinActive: "App protegido por PIN 🔒", activeStatus: "Ativo", privacyPolicy: "Privacidade", termsOfService: "Termos"
    }
  },
  it: {
    name: "Italiano", flag: "🇮🇹", t: {
      appName: "StarredList", tasks: "Attività", add: "Aggiungi", done: "Fatto", active: "Attivo",
      overdue: "Scaduto", total: "Totale", today: "Oggi", starred: "Preferiti", assistant: "Assistente",
      stats: "Statistiche", calendar: "Calendario", settings: "Impostazioni", profiles: "Profili",
      newTask: "Nuova", editTask: "Modifica", save: "Salva", cancel: "Annulla",
      title: "Titolo", notes: "Note", priority: "Priorità", category: "Categoria", dueDate: "Scadenza",
      tags: "Tag", subtasks: "Sottoattività", photo: "Foto", recurring: "Ricorrente", reminder: "Promemoria",
      high: "Alta", medium: "Media", low: "Bassa", noTasks: "Nessuna!", addFirst: "Tocca + per aggiungere",
      completionRate: "Tasso di compl.", thisWeek: "Questa sett.", byCategory: "Per categoria", byPriority: "Per priorità",
      export: "Esporta", share: "Condividi", lock: "Blocco", theme: "Tema", language: "Lingua", sound: "Suono",
      notifications: "Notifiche", profile: "Profilo", switchProfile: "Cambia profilo", newProfile: "Nuovo",
      pinLock: "Blocco PIN", enterPin: "Inserisci PIN", setPin: "Imposta PIN", wrongPin: "PIN errato",
      unlock: "Sblocca", confirmPin: "Conferma PIN", pinsNoMatch: "Non combaciano",
      daily: "Quoti.", weekly: "Settim.", monthly: "Mensile", never: "Mai",
      accentColor: "Colore", darkMode: "Scuro", completed: "Completato",
      goals: "Obiettivi", habits: "Abitudini", planner: "Agenda", collab: "Collaborare", board: "Bacheca", bot: "LIBI AI",
      appearanceHelp: "Aspetto, account e pref.", account: "Account",
      signedInWith: "Accesso con Google", signInWith: "Accedi con Google", syncTasks: "Sincronizza",
      signOut: "Esci", lightMode: "Luce", tapSwitchTheme: "Tocca per tema",
      notifSound: "Notifiche e Suono", getReminded: "Ricevi promemoria",
      soundEffects: "Effetti sonori", integrations: "Integrazioni", exportPdf: "Esporta in PDF",
      weeklyReport: "Report settimanale", installApp: "Installa App",
      addAppHome: "Aggiungi a schermata home", security: "Sicurezza",
      setPinLock: "Imposta blocco PIN", changePin: "Cambia PIN", protectApp: "Proteggi con PIN 4 cifre",
      pinActive: "Protetto da PIN 🔒", activeStatus: "Attivo", privacyPolicy: "Privacy", termsOfService: "Condizioni"
    }
  },
  ru: {
    name: "Русский", flag: "🇷🇺", t: {
      appName: "StarredList", tasks: "Задачи", add: "Добавить", done: "Готово", active: "Активно",
      overdue: "Просрок", total: "Всего", today: "Сегодня", starred: "Важное", assistant: "Ассистент",
      stats: "Статистика", calendar: "Календарь", settings: "Настройки", profiles: "Профили",
      newTask: "Новая", editTask: "Изменить", save: "Сохр.", cancel: "Отмена",
      title: "Название", notes: "Заметки", priority: "Приоритет", category: "Категория", dueDate: "Срок",
      tags: "Теги", subtasks: "Подзадачи", photo: "Фото", recurring: "Повтор", reminder: "Напом.",
      high: "Выс", medium: "Сред", low: "Низ", noTasks: "Нет задач!", addFirst: "Нажмите +",
      completionRate: "Успешность", thisWeek: "Эта неделя", byCategory: "По категории", byPriority: "По приоритету",
      export: "Экспорт", share: "Делиться", lock: "Блок", theme: "Тема", language: "Язык", sound: "Звук",
      notifications: "Уведомления", profile: "Профиль", switchProfile: "Сменить профиль", newProfile: "Новый",
      pinLock: "PIN-код", enterPin: "Ввод PIN", setPin: "Задать PIN", wrongPin: "Неверный PIN",
      unlock: "Разблок.", confirmPin: "Подтвердить", pinsNoMatch: "Не совпадает",
      daily: "Ежедн.", weekly: "Еженед.", monthly: "Ежемес.", never: "Никогда",
      accentColor: "Цвет", darkMode: "Темно", completed: "Завершено",
      goals: "Цели", habits: "Привычки", planner: "План", collab: "Сотруд-во", board: "Доска", bot: "LIBI AI",
      appearanceHelp: "Внешний вид, аккаунт", account: "Аккаунт",
      signedInWith: "Вход через Google", signInWith: "Войти с Google", syncTasks: "Синхронизация",
      signOut: "Выйти", lightMode: "Светло", tapSwitchTheme: "Сменить тему",
      notifSound: "Уведомления и звук", getReminded: "Напоминания о задачах",
      soundEffects: "Звуковые эффекты", integrations: "Интеграции", exportPdf: "Экспорт в PDF",
      weeklyReport: "Еженедельный отчет", installApp: "Установить App",
      addAppHome: "На главный экран", security: "Безопасность",
      setPinLock: "Задать PIN-код", changePin: "Изменить PIN", protectApp: "Защитите PIN-кодом",
      pinActive: "Защищено PIN 🔒", activeStatus: "Активно", privacyPolicy: "Политика конфид.", termsOfService: "Условия"
    }
  },
  zh: {
    name: "中文", flag: "🇨🇳", t: {
      appName: "StarredList", tasks: "任务", add: "添加", done: "已完成", active: "活动",
      overdue: "已过期", total: "总计", today: "今天", starred: "重要的", assistant: "助手",
      stats: "统计", calendar: "日历", settings: "设置", profiles: "配置",
      newTask: "新任务", editTask: "编辑", save: "保存", cancel: "取消",
      title: "标题", notes: "笔记", priority: "优先级", category: "类别", dueDate: "截止日期",
      tags: "标签", subtasks: "子任务", photo: "照片", recurring: "循环", reminder: "提醒",
      high: "高", medium: "中", low: "低", noTasks: "没有任务！", addFirst: "点击 + 添加",
      completionRate: "完成率", thisWeek: "本周", byCategory: "按分类", byPriority: "按优先级",
      export: "导出", share: "分享", lock: "锁定", theme: "主题", language: "语言", sound: "声音",
      notifications: "通知", profile: "个人资料", switchProfile: "切换资料", newProfile: "新资料",
      pinLock: "PIN 锁", enterPin: "输入 PIN", setPin: "设置 PIN", wrongPin: "PIN 错误",
      unlock: "解锁", confirmPin: "确认 PIN", pinsNoMatch: "PIN 不匹配",
      daily: "每天", weekly: "每周", monthly: "每月", never: "从不",
      accentColor: "主题色", darkMode: "深色", completed: "已完成",
      goals: "目标", habits: "习惯", planner: "每日计划", collab: "合作", board: "看板", bot: "LIBI AI",
      appearanceHelp: "外观、帐户和偏好", account: "帐户",
      signedInWith: "已使用 Google 登录", signInWith: "使用 Google 登录", syncTasks: "同步任务",
      signOut: "登出", lightMode: "浅色", tapSwitchTheme: "点击切换主题",
      notifSound: "通知和声音", getReminded: "获取任务提醒",
      soundEffects: "操作音效", integrations: "集成", exportPdf: "导出 PDF",
      weeklyReport: "任务与进度周报", installApp: "安装应用",
      addAppHome: "添加到主屏幕", security: "安全",
      setPinLock: "设置 PIN 锁", changePin: "更改 PIN", protectApp: "使用 4 位 PIN 码保护应用",
      pinActive: "应用由 PIN 保护 🔒", activeStatus: "活跃的", privacyPolicy: "隐私政策", termsOfService: "服务条款"
    }
  },
  ja: {
    name: "日本語", flag: "🇯🇵", t: {
      appName: "StarredList", tasks: "タスク", add: "追加", done: "完了", active: "アクティブ",
      overdue: "期限切れ", total: "全体", today: "今日", starred: "お気に入り", assistant: "アシスタント",
      stats: "統計", calendar: "カレンダー", settings: "設定", profiles: "プロファイル",
      newTask: "新しい", editTask: "編集", save: "保存", cancel: "キャンセル",
      title: "タイトル", notes: "メモ", priority: "優先度", category: "カテゴリ", dueDate: "期限",
      tags: "タグ", subtasks: "サブタスク", photo: "写真", recurring: "繰り返し", reminder: "リマインダー",
      high: "高", medium: "中", low: "低", noTasks: "タスクなし！", addFirst: "+ で追加",
      completionRate: "完了率", thisWeek: "今週", byCategory: "カテゴリ別", byPriority: "優先度別",
      export: "エクスポート", share: "共有", lock: "ロック", theme: "テーマ", language: "言語", sound: "音",
      notifications: "通知", profile: "プロファイル", switchProfile: "プロファイル切替", newProfile: "新規",
      pinLock: "PINロック", enterPin: "PIN入力", setPin: "PIN設定", wrongPin: "PINが違います",
      unlock: "ロック解除", confirmPin: "PIN確認", pinsNoMatch: "一致しません",
      daily: "毎日", weekly: "毎週", monthly: "毎月", never: "なし",
      accentColor: "アクセントカラー", darkMode: "ダーク", completed: "完了",
      goals: "目標", habits: "習慣", planner: "デイリープランナー", collab: "協力", board: "ボード", bot: "LIBI AI",
      appearanceHelp: "外観、アカウントと設定", account: "アカウント",
      signedInWith: "Googleでログイン済み", signInWith: "Googleでログイン", syncTasks: "同期",
      signOut: "ログアウト", lightMode: "ライト", tapSwitchTheme: "テーマ切り替え",
      notifSound: "通知とサウンド", getReminded: "タスクのリマインダー",
      soundEffects: "効果音", integrations: "連携", exportPdf: "PDF出力",
      weeklyReport: "週次レポート", installApp: "アプリをインストール",
      addAppHome: "ホーム画面に追加", security: "セキュリティ",
      setPinLock: "PINロック設定", changePin: "PIN変更", protectApp: "4桁のPINで保護",
      pinActive: "PIN保護中 🔒", activeStatus: "アクティブ", privacyPolicy: "プライバシーポリシー", termsOfService: "利用規約"
    }
  },
  ko: {
    name: "한국어", flag: "🇰🇷", t: {
      appName: "StarredList", tasks: "할일", add: "추가", done: "완료", active: "진행중",
      overdue: "기한지남", total: "전체", today: "오늘", starred: "중요", assistant: "비서",
      stats: "통계", calendar: "캘린더", settings: "설정", profiles: "프로필",
      newTask: "새로운", editTask: "편집", save: "저장", cancel: "취소",
      title: "제목", notes: "메모", priority: "중요도", category: "카테고리", dueDate: "기한",
      tags: "태그", subtasks: "하위 할일", photo: "사진", recurring: "반복", reminder: "알림",
      high: "높음", medium: "중간", low: "낮음", noTasks: "할일이 없습니다!", addFirst: "+ 를 눌러 추가",
      completionRate: "달성률", thisWeek: "이번 주", byCategory: "카테고리별", byPriority: "중요도별",
      export: "내보내기", share: "공유", lock: "잠금", theme: "테마", language: "언어", sound: "소리",
      notifications: "알림", profile: "프로필", switchProfile: "변경", newProfile: "새로운",
      pinLock: "PIN 잠금", enterPin: "PIN 입력", setPin: "PIN 설정", wrongPin: "잘못된 PIN",
      unlock: "잠금해제", confirmPin: "PIN 확인", pinsNoMatch: "일치하지 않음",
      daily: "매일", weekly: "매주", monthly: "매월", never: "안함",
      accentColor: "강조 색상", darkMode: "다크", completed: "완료",
      goals: "목표", habits: "습관", planner: "계획", collab: "협업", board: "보드", bot: "LIBI AI",
      appearanceHelp: "모양, 계정 및 기본 설정", account: "계정",
      signedInWith: "Google로 로그인됨", signInWith: "Google로 로그인", syncTasks: "동기화",
      signOut: "로그아웃", lightMode: "라이트", tapSwitchTheme: "테마 변경",
      notifSound: "알림 및 사운드", getReminded: "할일 알림 받기",
      soundEffects: "효과음", integrations: "연동", exportPdf: "PDF로 내보내기",
      weeklyReport: "주간 보고서", installApp: "앱 설치",
      addAppHome: "홈 화면에 추가", security: "보안",
      setPinLock: "PIN 잠금 설정", changePin: "PIN 변경", protectApp: "4자리 PIN으로 보호",
      pinActive: "PIN 보호됨 🔒", activeStatus: "진행중", privacyPolicy: "개인정보 처리방침", termsOfService: "이용 약관"
    }
  }
};`;

const matchStart = code.indexOf('export const LANGS');
const matchEnd = code.indexOf('export const ACCENTS');

const modified = code.substring(0, matchStart) + newLangs + '\n\n' + code.substring(matchEnd);
fs.writeFileSync('c:/Users/isaac/taskflow/taskflow/src/utils/constants.js', modified);
console.log('constants updated!');
