name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore starredlist.keystore \
            -alias starredlist \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "MxuWBccYftZ8Ev/a6BGD5myEzoqVSP5h" \
            -keypass "MxuWBccYftZ8Ev/a6BGD5myEzoqVSP5h" \
            -dname "CN=Isaac Titus, OU=StarredList, O=LIBI Labs, L=Kerala, ST=Kerala, C=IN"

      - name: Base64 encode keystore
        run: base64 -w 0 starredlist.keystore > keystore_base64.txt

      - name: Print to summary
        run: |
          echo "## Copy this base64 string into a GitHub Secret" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat keystore_base64.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
